tasks:
  - init: |
      docker pull gvenzl/oracle-xe:21-slim 
      docker run -d -p 1521:1521 --name oracle-database-xe -e ORACLE_PASSWORD=TheSuperSecret1509! -e APP_USER=APP -e APP_USER_PASSWORD=APPPW gvenzl/oracle-xe:21-slim &&
      # open the readme.md document in VS code; note: thanks to the configuration in .vscode/settings.json, the document opens in markdown preview mode
      #gp open README.md
      alias sql="/workspace/oracle_xe_slim/sqlcl/bin/sql"
      wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip && unzip -q sqlcl-latest.zip && 
      echo "done with download and unzip SQLcl and now sleep for 20 seconds until db is running" 
      sleep 20s &&       
      gp sync-done database-running &&
      touch db-running &&
      /workspace/oracle_xe_slim/sqlcl/bin/sql sys/"TheSuperSecret1509!"@localhost:1521/xe as sysdba @".prepare/create-user-dev"
  - name: start container and run SQL*Plus session as user SysDBA
    init: gp sync-await database-running
    command: |
      docker start oracle-database-xe  &&
      docker ps &&  
      sleep 3s && 
      echo "Oracle Database XE is running. The database is accessible at localhost, port 1521; database SID = XE and has an additional user APP/APPPW in PDB XEPDB1 " && 
      gp sync-done database-started &&
      docker exec -it oracle-database-xe sqlplus sys/TheSuperSecret1509! as sysdba
  - name: Open SQLcl for user DEV
    init: |
      gp sync-await database-running
    command: |
      gp sync-await database-started &&
      /workspace/oracle_xe_slim/sqlcl/bin/sql DEV/DEV_PW@localhost:1521/xepdb1 

ports:

  # Oracle Database XE
  - port: 1521
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - Oracle.oracledevtools
