ALTER SESSION SET CONTAINER=XEPDB1 SERVICE=xepdb1;

CREATE USER DEV IDENTIFIED BY "DEV_PW" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM TO DEV;

connect DEV/DEV_PW@localhost:1521/xepdb1

show user
